### ISSUE TITLE
Install-Package TimeZoneConverter

### ISSUE THREAD

**Issue by abiyek** [mj1856/mj1856#1]
Hello Matt, 

I was trying to run your project following readme instruction I ran in to the problem shown below. 
Can you help? I tried to research it but I keep on running to the wall, definitely not understanding what's going on. I keep getting net45 is not available so I can't use NodaTime as a reference. 

Thanks for all your help and time in advance.

Regards, 

-aK> 

PM> Install-Package TimeZoneConverter
Restoring packages for C:\Users\aK\Documents\DOTNetCore\TimeZoneConverter-master\src\TimeZoneConverter\TimeZoneConverter.csproj...
Install-Package : NU1108: Cycle detected. 
  TimeZoneConverter -> TimeZoneConverter (>= 3.2.0).
At line:1 char:1
+ Install-Package TimeZoneConverter
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'TimeZoneConverter'.
At line:1 char:1
+ Install-Package TimeZoneConverter
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:02.2546514
PM> install-package CommandLineParser
Restoring packages for C:\Users\aK\Documents\DOTNetCore\TimeZoneConverter-master\src\TimeZoneConverter\TimeZoneConverter.csproj...
  GET https://api.nuget.org/v3-flatcontainer/commandlineparser/index.json
  OK https://api.nuget.org/v3-flatcontainer/commandlineparser/index.json 156ms
  GET https://api.nuget.org/v3-flatcontainer/commandlineparser/2.8.0/commandlineparser.2.8.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/commandlineparser/2.8.0/commandlineparser.2.8.0.nupkg 137ms
Installing CommandLineParser 2.8.0.
Restoring packages for C:\Users\aK\Documents\DOTNetCore\TimeZoneConverter-master\src\TimeZoneConverter\TimeZoneConverter.csproj...
  CACHE https://api.nuget.org/v3-flatcontainer/commandlineparser/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/commandlineparser/2.8.0/commandlineparser.2.8.0.nupkg
Installing NuGet package CommandLineParser 2.8.0.
Committing restore...
Writing assets file to disk. Path: C:\Users\aK\Documents\DOTNetCore\TimeZoneConverter-master\src\TimeZoneConverter\obj\project.assets.json
Restored C:\Users\aK\Documents\DOTNetCore\TimeZoneConverter-master\src\TimeZoneConverter\TimeZoneConverter.csproj (in 191 ms).
Successfully installed 'CommandLineParser 2.8.0' to TimeZoneConverter
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\aK\Documents\DOTNetCore\TimeZoneConverter-master\test\TimeZoneConverter.Tests\obj\project.assets.json
Restored C:\Users\aK\Documents\DOTNetCore\TimeZoneConverter-master\test\TimeZoneConverter.Tests\TimeZoneConverter.Tests.csproj (in 29 ms).

NuGet Config files used:
    C:\Users\aK\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
    C:\Program Files (x86)\NuGet\Config\Xamarin.Offline.config

Feeds used:
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
All projects are up-to-date for restore.
Executing nuget actions took 1.5 sec
Time Elapsed: 00:00:03.7917744
PM> Install-Package TimeZoneConverter
Restoring packages for C:\Users\aK\Documents\DOTNetCore\TimeZoneConverter-master\src\TimeZoneConverter\TimeZoneConverter.csproj...
Install-Package : NU1108: Cycle detected. 
  TimeZoneConverter -> TimeZoneConverter (>= 3.2.0).
At line:1 char:1
+ Install-Package TimeZoneConverter
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'TimeZoneConverter'.
At line:1 char:1
+ Install-Package TimeZoneConverter
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:01.1493007
PM> Install-Package TimeZoneConverter.Posix
Restoring packages for C:\Users\aK\Documents\DOTNetCore\TimeZoneConverter-master\src\TimeZoneConverter\TimeZoneConverter.csproj...
Restoring packages for C:\Users\aK\Documents\DOTNetCore\TimeZoneConverter-master\src\TimeZoneConverter\TimeZoneConverter.csproj...
Install-Package : NU1108: Cycle detected. 
  TimeZoneConverter -> TimeZoneConverter.Posix 2.1.0 -> TimeZoneConverter (>= 3.1.0).
At line:1 char:1
+ Install-Package TimeZoneConverter.Posix
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'TimeZoneConverter'.
At line:1 char:1
+ Install-Package TimeZoneConverter.Posix
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by mj1856** [comment]
Hi.  This is the repository for my personal home page, not TimeZoneConverter.

That said, it looks like you're trying to install TimeZoneConverter *into TimeZoneConverter* - hence "Cycle Detected".

If you want to use TimeZoneConverter, install the package into your own project.  You don't need the source code to do that.
